version: '3'
services:
  tayko.co:
    container_name: tayko.co
    image: 
    restart: always
    expose:
      - "80"
    networks:
      - web
    labels:
      - "traefik.backend=tayko.co"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:tayko.co"
      - "traefik.enabled=true"
      - "traefik.port=80"
      - "traefik.default.protocol=http"
        
networks:
  web:
    external: true