apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tayko-co-pvc
  labels:
    app: tayko-co
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi