apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tayko-co-pvc
  labels:
    app: tayko-co
spec:
  storageClassName: tayko-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi