{{- $fullName := include "tayko-co.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: {{ $fullName }}
    annotations:
        kubernetes.io/ingress.class: traefik
spec:
    rules:
    {{- range .Values.ingress.hosts }}
        - host: {{ .host }}
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: {{ $fullName }}
                        servicePort: http
    {{- end }}
